### ISSUE TITLE
metalsmith-link-checker hangs for ever

### ISSUE THREAD

**Issue by NightTsarina** [emmercm/metalsmith-plugins#16]
Hi,

Today I tried using your plugin to check for broken links in a metalsmith-generated site; I added it as the last plugin, so it would see the final state of the website, but when I try to build it it just hangs in what looks like a spin loop. Using `DEBUG=*` gives me no clues, as the plugin is not logging at all; strace was not useful eiter: I only see calls to `futex` and `getpid` while using 100% CPU. Any idea what could cause this?

As a side note, it would be very useful if the plugin logged its progress to see where it is stuck.

Thanks.

**Comment by emmercm** [comment]
Hi @NightTsarina, thanks for the bug report. It will be hard to know what is happening in your unique situation without logging in, so I'll look at adding some.

I haven't touched my Metalsmith plugins since migrating them to this monorepo, so I need to spend some time getting them up and running on CI/CD again.

**Comment by emmercm** [comment]
https://github.com/emmercm/metalsmith-plugins/pull/57 will add many debug logs in most of my plugins. Please let me know if this helps you debug your specific issue.

**Comment by NightTsarina** [comment]
Thanks! I will give it a go as soon as possible
